const fs = require('fs');
const path = require('path');

// Use Netlify env var NETLIFY_API_BASE_URL or fallback to API_BASE_URL or localhost
const apiBase = process.env.NETLIFY_API_BASE_URL || process.env.API_BASE_URL || 'http://localhost:3001';
const content = `// Generated by scripts/generate-config.js
window.API_BASE_URL = '${apiBase.replace(/\/+$/,'')}';
`;

const outPath = path.join(__dirname, '..', 'api-config.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('Wrote', outPath, 'with API base:', apiBase);
